import { cn } from "@/lib/utils";

export function Card({ className, ...props }: React.ComponentProps<"div">) { return <div className={cn("rounded-3xl border border-white/8 bg-card p-5 shadow-[0_18px_50px_rgba(0,0,0,.18)]", className)} {...props} />; }
export function Input({ className, ...props }: React.ComponentProps<"input">) { return <input className={cn("h-12 w-full rounded-2xl border border-white/10 bg-white/[.045] px-4 text-[16px] text-white outline-none transition placeholder:text-zinc-600 focus:border-amber-300/60 focus:ring-4 focus:ring-amber-300/10", className)} {...props} />; }
export function Label({ className, ...props }: React.ComponentProps<"label">) { return <label className={cn("mb-2 block text-sm font-medium text-zinc-300", className)} {...props} />; }
export function Textarea({ className, ...props }: React.ComponentProps<"textarea">) { return <textarea className={cn("min-h-24 w-full rounded-2xl border border-white/10 bg-white/[.045] p-4 text-[16px] outline-none focus:border-amber-300/60", className)} {...props} />; }
export function Skeleton({ className }: { className?: string }) { return <div aria-hidden className={cn("animate-pulse rounded-2xl bg-white/8", className)} />; }
export function PageTitle({ eyebrow, title, description }: { eyebrow?: string; title: string; description?: string }) { return <header className="mb-6"><p className="mb-2 text-xs font-semibold uppercase tracking-[.22em] text-amber-300">{eyebrow}</p><h1 className="text-3xl font-semibold tracking-tight text-white">{title}</h1>{description && <p className="mt-2 max-w-md text-sm leading-6 text-zinc-400">{description}</p>}</header>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <Card className="py-10 text-center"><p className="font-medium text-white">{title}</p><p className="mx-auto mt-2 max-w-sm text-sm text-zinc-400">{description}</p></Card>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <Card className="border-red-400/20 bg-red-400/5 text-center"><p className="text-sm text-red-200">{message}</p>{retry && <button className="mt-4 min-h-11 rounded-xl border border-red-300/20 px-4 text-sm font-semibold" onClick={retry}>Riprova</button>}</Card>; }
export function FieldError({ children }: { children?: React.ReactNode }) { return children ? <p role="alert" className="mt-1.5 text-xs text-red-300">{children}</p> : null; }
